<?php

use IanRothmann\AINinja\AINinja;

it('can extract themes', function () {
    $handler = new AINinja;

    $text= <<<TOC
 638
                                    F. J. DYSON [September
                                    but not a tragic one, since MacDonald cleaned up the whole subject very happily without any help from me. The only thing he did not clean up is the case d = 26, which remains a tantalizing mystery [14].
                                    3. The Maxwell equations. I have digressed too long on this story of modular forms and Lie algebras, which I mentioned only because it is an example of a missed opportunity that happened to me personally. I now return to my main theme, the discussion of missed opportunities that were important in the historical development of mathematics.
                                    The first clear sign of a breakdown in communication between physics and mathematics was the extraordinary lack of interest among mathemati- cians in James Clerk Maxwell's discovery of the laws of electromagnetism. Maxwell discovered his equations, which describe the behavior of electric and magnetic fields under the most general conditions, in the year 1861, and published a clear and definitive statement of them [15] in 1865. This was the great event of nineteenth century physics, achieving for electricity and magnetism what Newton had achieved for gravitation two hundred years earlier. Maxwell's equations contained, among other things, the explanation of light as an electromagnetic phenomenon, and the basic principles of electric power transmission and radio technology. These aspects of the theory were of primary interest to physicists and engineers. But in addition to their physical applications, Maxwell's equations had abstract mathematical qualities which were profoundly new and important. Maxwell's theory was formulated in terms of a new style of mathematical concept, a tensor field extending throughout space and time and obeying coupled partial differential equations of peculiar symmetry.
                                    After Newton's laws of gravitational dynamics had been promulgated in 1687, the mathematicians of the eighteenth century seized hold of these laws and generalized them into the powerful mathematical theory of analytical mechanics. Through the work of Euler, Lagrange and Hamilton, the equations of Newton were analyzed and understood in depth. Out of this deep exploration of Newtonian physics, new branches of pure mathematics ultimately emerged. Lagrange distilled from the extremal properties of dynamical integrals the general principles of the calculus of variations. Fifty years later the work of Euler on geodesic motions led Gauss to the creation of differential geometry. Another fifty years later, the generalization of the Hamilton-Jacobi formulation of dynamics led Lie to the invention of Lie groups. And finally, the last gift of Newtonian physics to pure mathematics was the work of Poincaré on the qualitative behavior of orbits which led to the birth of modern topology.

                                    1972] MISSED OPPORTUNITIES 639
                                    But the mathematicians of the nineteenth century failed miserably to grasp the equally great opportunity offered to them in 1865 by Maxwell. If they had taken Maxwell's equations to heart as Euler took Newton's, they would have discovered, among other things, Einstein's theory of special relativity, the theory of topological groups and their linear repre- sentations, and probably large pieces of the theory of hyperbolic differen- tial equations and functional analysis. A great part of twentieth century physics and mathematics could have been created in the nineteenth century, simply by exploring to the end the mathematical concepts to which Maxwell's equations naturally lead.
                                    There is plenty of documentary evidence showing how Maxwell's theory appeared to the mathematicians of his time. I shall quote two short extracts to illustrate contrasting ways in which the theory was brought to their attention. Both are taken from Presidential Addresses to meetings of the British Association, then as now the chief organization in Britain dedicated to promoting the unity of science. First comes Maxwell him- self, speaking in 1870, his announced topic being the relation between mathematics and physics [16].
                                    "According to a theory of electricity which is making great progress in Germany, two electrical particles act on one another directly at a dis- tance, but with a force which, according to Weber, depends on their relative velocity, and according to a theory hinted at by Gauss, and developed by Riemann, Lorenz, and Neumann, acts not instantaneously, but after a time depending on the distance. The power with which this theory, in the hands of these eminent men, explains every kind of electrical phenomena must be studied in order to be appreciated. Another theory of electricity which I prefer denies action at a distance and attributes electric action to tensions and pressures in an all-pervading medium, these stresses being the same in kind with those familiar to engineers, and the medium being identical with that in which light is supposed to be prop- agated."
                                    It is difficult to read Maxwell's address without being infuriated by his excessive modesty, which led him to refer to his epoch-making discovery of nine years earlier as only "Another theory of electricity which I prefer." How different is his style from that of Newton, who wrote at the beginning of the third book of his Principia [17], "It remains that, from the same principles, I now demonstrate the frame of the System of the World." Since Maxwell himself seemed so half-hearted, it is not surprising that he did not inspire the mathematicians to throw aside their fashionable covariants and quantics and study his equations.
                                    My second quotation is from the Oxford mathematician, Henry Smith, speaking three years later to the same audience [18]. A few months

                                    640 F. J. DYSON [September
                                    before he spoke in 1873, Maxwell's great book on electricity and magnet- ism had appeared [19].
                                    "In the course of the present year a treatise on electricity has been published by Professor Maxwell, giving a complete account of the mathe- matical theory of that science, No mathematician can turn over the pages of these volumes without very speedily convincing himself that they contain the first outlines (and something more than the first outlines) of a theory which has already added largely to the methods and resources of pure mathematics, and which may one day render to that abstract science services no less than those which it owes to astronomy. For elec- tricity now, like astronomy of old, has placed before the mathematician an entirely new set of questions, requiring the creation of entirely new methods for their solution, It must be considered fortunate for the mathematicians that such a vast field of research in the application of mathematics to physical enquiries should be thrown open to them, at the very time when the scientific interest in the old mathematical astron- omy has for the moment flagged, — "
                                    These words show that at least one mathematician did understand the historic nature of the challenge presented to mathematics by Maxwell's work. Smith's perception is the more remarkable, considering that he was a very pure mathematician whose best-known work is in analytic number theory. Unfortunately he was then 46 years old, too old to be a pioneer in a new field. No doubt he contented himself with "turning over the pages of these volumes" and then returned with relief to his familiar ternary forms. The young men, who might have been stimulated by his words to create new fields of mathematics, were not listening. Hermann Minkowski and Jacques Hadamard, who were to achieve in the twentieth century the fulfilment of some of Smith's prophecies, were boys of nine and eight at the time he spoke. Élie Cartan was three; Hermann Weyl, Jean Leray and Harish-Chandra were not yet born.
                                    Hermann Minkowski had something to say thirty-five years later about the opportunity which the mathematicians had missed. He was talking to the German equivalent of the British Association, three years after Einstein's discovery of special relativity. He pointed out that the mathematical basis of Einstein's discovery lies in an incompatibility between two groups of transformations of space and time coordinates. On the one hand, the equations of Newtonian mechanics are invariant under a group G^ which physicists now call the Galilei group. The group Goo is six-dimensional; it is generated by three rotations of the space coordinates, and three uniform velocity transformations of the form
                                    (4) X-»X—Ut, t-» t.
TOC;


    $result = $handler->extractThemes()
        ->fromText($text)
        ->get();

    expect($result->getThemes())->toHaveCount(3);
    expect($result->getSummary())->toBeString();
});
